### ISSUE TITLE
Minutes sub tab

### ISSUE THREAD

**Issue by CarletonSSS** [abejfehr/CSSS#38]
Does the minutes sub tab under documents go anywhere? It takes me to the same place as clicking documents does, so i want wondering if we should just scrap that sub tab

**Comment by abejfehr** [comment]
It's not _quite_ the same, but we may as well scrap that link anyways. If there was a ton of content on the documents page, clicking the "minutes" link would send you to the minutes section of the documents page. But because the page has almost no content and the whole thing fits on one screen, you don't notice that feature.

**Comment by abejfehr** [comment]
Removed!
